### PR TITLE
Potentially fix #3180

### LINKED ISSUE #3180: Jackhammer doesn't dig deepslate
**Describe the error**
Jackhammers (basic, advanced, industrial) do not dig deep shale, basalt, netherak and endernyak. Ore from mods does not drip correctly.

**Reproduction Steps**
- Take a charged industrial jackhammer from the creative, enchant it for efficiency 5 and silk touch.
- Try to mine a stone (everything is ok)
- Try to mine a stone next to the ore from Tech Reborn (the ore will fall out)
- Try to mine a stone next to ore from Minecraft (the ore will not fall out)
- Try to mine andesite, diorite and granite (everything is ok). But for some reason smooth basalt, basalt and calcite are not mined.
- Try to mine an end stone (slowly)
- Try to mine a netherrack (slowly)
- Try to mine deepslate (slowly)
- Try to mine tuff (slowly)

**Screenshots**
Added gifs via the link for additional context

**Environment (please include the following information along with the version):**
   - Minecraft: 1.20.1
   - Mod loader: cloth 0.14.22 for 1.20.1

**Magazines**
Not required

**Additional context**
https://imgur.com/a/BKAhMNW

### PR DESCRIPTION
**Pull request by xanthian**
Adds a new tag JACKHAMMER_MINABLE
Which includes BASE_STONE_OVERWORLD & BASE_STONE_NETHER as wall as C:STONE
Amended JackhammerItem to include the check for the newly created tag.

only thing this wont fix is Endstone 🤷‍♂️

### CODE REVIEW

File: src/main/java/techreborn/items/tool/JackhammerItem.java [hunk 1]
```diff
@@ -60,7 +60,8 @@ public float getMiningSpeedMultiplier(ItemStack stack, BlockState state) {
 		if (getStoredEnergy(stack) < cost) return unpoweredSpeed;
 		if (ToolsUtil.JackHammerSkippedBlocks(state)) return unpoweredSpeed;
 
-		if (state.isIn(BlockTags.STONE_ORE_REPLACEABLES)) {
+		if (state.isIn(TRContent.BlockTags.JACKHAMMER_MINEABLE)) {
```
Comment (modmuss50) [inline src/main/java/techreborn/items/tool/JackhammerItem.java:65]: Missing `import techreborn.init.TRContent`
